### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by artembogomaz-zh** [XRPLF/xrpl.js#2208] opened 2023-02-15 08:14 UTC
In some cases it raised UnhandledPromiseRejection and not catches by catch clause, function is async:
"xrpl": "^2.7.0-beta.0"

My code:

```
const client = new XrplClient(process.env.RIPPLE_NODE)
    try {
        await client.connect()

        const account_info = await client.request(address)

        console.log(account_info)
        const flags = xrpl.parseAccountRootFlags(account_info.result.account_data.Flags)
        client.disconnect()

        return flags.lsfRequireDestTag

    } catch (error) {
        console.log(`ERROR received : ${error}`);
        return false
    }

```

Error

```
Unhandled Promise Rejection
{
   "errorType":"Runtime.UnhandledPromiseRejection",
   "errorMessage":"Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('reconnect')",
   "reason":{
      "errorType":"Error",
      "errorMessage":"Unhandled error. ('reconnect')",
      "code":"ERR_UNHANDLED_ERROR",
      "context":"reconnect",
      "stack":[
         "Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('reconnect')",
         "    at Client.emit (events.js:303:17)",
         "    at Connection.<anonymous> (/var/task/node_modules/xrpl/dist/npm/client/index.js:94:18)",
         "    at Connection.emit (events.js:314:20)",
         "    at /var/task/node_modules/xrpl/dist/npm/client/connection.js:300:22",
         "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
      ]
   },
   "promise":{
      
   },
   "stack":[
      "Runtime.UnhandledPromiseRejection: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('reconnect')",
      "    at process.<anonymous> (/var/runtime/index.js:35:15)",
      "    at process.emit (events.js:314:20)",
      "    at processPromiseRejections (internal/process/promises.js:209:33)",
      "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
   ]
}
```

**Comment by mvadari** [comment] 2023-02-15 14:32
`client.disconnect` is an async method.

**Comment by artembogomaz-zh** [comment] 2023-02-16 04:52
@mvadari Thanks for answer, will try on my side to add await. Not sure why documentation is without await for this method

**Comment by artembogomaz-zh** [comment] 2023-02-16 04:52
More-more, as I am running this function in AWS Lambda, unhandled exception totally destroying it

**Comment by artembogomaz-zh** [comment] 2023-02-16 08:23
Didn't work for me

**Comment by JST5000** [comment] 2023-02-16 20:41
Your example code is using `XrplClient`, which is from a different library called `xrpl-client` - https://www.npmjs.com/package/xrpl-client 

The client in `xrpl.js` is just called `Client` https://js.xrpl.org/classes/Client.html - is that the issue?

**Comment by artembogomaz-zh** [comment] 2023-02-17 08:54
@JST5000 I am using `xrpl.js Client` actually ( in my code above I just renamed it), the unhandled exception pointing to `xrpl.js` library `xrpl/dist/npm/client/index.js:94:18` and `/var/task/node_modules/xrpl/dist/npm/client/connection.js:300:22`

**Comment by JST5000** [comment] 2023-02-17 19:47
Hmmm... For some additional context could you share
* The value of `process.env.RIPPLE_NODE`
* What version of node you're using
* What line of the sample code does the error happen at? (My assumption is it's happening at `await client.connect()` but I could be wrong)

**Comment by zain-ekkel** [comment] 2023-07-31 09:52
Hey @JST5000 ,
I am facing the exact same issue and package "xrpl": "^2.7.0". My specs: 
1. **wss://xrplcluster.com**
2. node version **v16.18.0**
3. I am not sure where the error is happening because it is not mention here in the logs. Strange thing is it works fine with all the queries and after some time just stop working and takes down the server with it. 

`Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('reconnect')
    at new NodeError (node:internal/errors:387:5)
    at Client.emit (node:events:502:17)
    at Connection.<anonymous> (/home/ubuntu/hurrian-token-migration/api/node_modules/xrpl/dist/npm/client/index.js:94:18)
    at Connection.emit (node:events:513:28)
    at /home/ubuntu/hurrian-token-migration/api/node_modules/xrpl/dist/npm/client/connection.js:296:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'reconnect'`

**Comment by JST5000** [comment] 2023-07-31 14:59
@zain-ekkel Would you be able to share the code where the issue was happening for you? (Or does running the above snippet cause the issue to happen locally for you as well?)

My current theory is that `wss://xrplcluster.com` is rate limiting requests, and shutting off the connection. Then the library tries to reconnect behind the scenes and is rejected from connecting, resulting in the `ERR_UNHANDLED_ERROR`.

**Comment by artembogomaz-zh** [comment] 2023-08-01 03:24
On my side I fixed it removing library from project and using API calls directly. With API works perfect, so definitely some issues with library.

**Comment by zain-ekkel** [comment] 2023-08-01 06:01
@JST5000 , sure
Before
`
const RPC_ENDPOINT = 'wss://xrplcluster.com'
const client = new Client(RPC_ENDPOINT);
export const checkMLDBalance = async (
  xrp_address: string,
  avax_address: string,
  tx_hashes: string[]
) => {
  try {
    await client.connect();
    const res = await client.request({
      command: "account_tx",
      account: xrp_address,
      forward: false,
      binary: false,
      limit: 50,
    });

    /* internal logic */
      await client.disconnect();
  } catch (error) {
    console.log(error);
    return null;
  }
}; `

I also tried using try catch with Client class to only throw error and don't close the whole server but it is still throwing the error and closing the server.  
`
const getXRPClient = () => {
  try {
    const _client = new Client(RPC_ENDPOINT);
    return _client;
  } catch (error) {
    console.log(error);
    return null;
  }
};
`

**Comment by zain-ekkel** [comment] 2023-08-01 06:06
@JST5000 , sure
Before

```javascript
const RPC_ENDPOINT = 'wss://xrplcluster.com'
const client = new Client(RPC_ENDPOINT);
export const checkMLDBalance = async (
  xrp_address: string,
  avax_address: string,
  tx_hashes: string[]
) => {
  try {
    await client.connect();
    const res = await client.request({
      command: "account_tx",
      account: xrp_address,
      forward: false,
      binary: false,
      limit: 50,
    });

    /* internal logic */
      await client.disconnect();
  } catch (error) {
    console.log(error);
    return null;
  }
}; ```

I also tried using try catch with Client class to only throw error and don't close the whole server but it is still throwing the error and closing the server.  
```
const getXRPClient = () => {
  try {
    const _client = new Client(RPC_ENDPOINT);
    return _client;
  } catch (error) {
    console.log(error);
    return null;
  }
};
```

**Comment by zain-ekkel** [comment] 2023-08-01 06:08
@JST5000 , sure

```javascript
const RPC_ENDPOINT = 'wss://xrplcluster.com'
const client = new Client(RPC_ENDPOINT);
export const checkMLDBalance = async (
  xrp_address: string,
  avax_address: string,
  tx_hashes: string[]
) => {
  try {
    await client.connect();
    const res = await client.request({
      command: "account_tx",
      account: xrp_address,
      forward: false,
      binary: false,
      limit: 50,
    });

    /* internal logic */
      await client.disconnect();
  } catch (error) {
    console.log(error);
    return null;
  }
}; ```


I also tried using try catch with Client class to only throw error and don't close the whole server but it is still throwing the error and closing the server.  


```javascript
const getXRPClient = () => {
  try {
    const _client = new Client(RPC_ENDPOINT);
    return _client;
  } catch (error) {
    console.log(error);
    return null;
  }
};
```

**Comment by zain-ekkel** [comment] 2023-08-01 06:10
@JST5000 , sure and I also tried using try catch with Client class to only throw error and don't close the whole server but it is still throwing the error and closing the server.  

```javascript
const RPC_ENDPOINT = 'wss://xrplcluster.com'
const client = new Client(RPC_ENDPOINT);
export const checkMLDBalance = async (
  xrp_address: string,
  avax_address: string,
  tx_hashes: string[]
) => {
  try {
    await client.connect();
    const res = await client.request({
      command: "account_tx",
      account: xrp_address,
      forward: false,
      binary: false,
      limit: 50,
    });

    /* internal logic */
      await client.disconnect();
  } catch (error) {
    console.log(error);
    return null;
  }
}; 

const getXRPClient = () => {
  try {
    const _client = new Client(RPC_ENDPOINT);
    return _client;
  } catch (error) {
    console.log(error);
    return null;
  }
};
```

**Comment by JST5000** [comment] 2023-08-01 10:50
@zain-ekkel I'm unfortunately unable to reproduce locally, but I did learn that you may be able to stop the error from propagating by using `.catch` on the promise instead of `try { ... } catch { ... }`. 

StackOverflow answer with a bit more context: https://stackoverflow.com/a/64562922

If you add 
```
.catch(error => {
    console.log('<promise that's failing>:', error)
  });
```
to the promises (in this case, `client.connect()`, `client.request()`, and `client.disconnect()` then it may prevent this from happening. 

It's not a great solution, but I've tried reproducing with no luck, and I haven't been able to find where the issue would be coming from by looking at the code. 

I'll share what I tried and what I noticed below for context.

### Attempts to reproduce

First, I attempted to reproduce using both of your above codes. For @artembogomaz-zh I ran this script which matched the code you provided. 2000 iterations translated to roughly 45 minutes of runtime, during which no errors popped up.
```
import { Client, parseAccountRootFlags, AccountInfoRequest } from "xrpl";

const RPC_ENDPOINT = "wss://xrplcluster.com";
const client = new Client(RPC_ENDPOINT);

async function sendRequest() {
  const client = new Client(RPC_ENDPOINT);
  // Custom code added to make it compile - I assumed the `address` variable was an `AccountInfoRequest`
  const address: AccountInfoRequest = {
    command: "account_info",
    account: "rJ6mzxnRNJYMUZ4nq8HxM2udKXrxDTVr9h",
  };
  // End of custom code
  try {
    await client.connect();

    const account_info = await client.request(address);

    const flags = parseAccountRootFlags(account_info.result.account_data.Flags);
    client.disconnect();

    return flags.lsfRequireDestTag;
  } catch (error) {
    console.log(`ERROR received : ${error}`);
    return false;
  }
}

async function main() {
  const timeout = 0;
  for (let i = 0; i < 2000; i++) {
    console.log(i);
    await new Promise((resolve) => setTimeout(resolve, timeout));
    await sendRequest();
  }
}

main();
```

(The timeout = 0 was an artifact from previous experiments, but shouldn't impact the results as far as I can tell and I want to copy the code exactly)

To try reproducing the error with @zain-ekkel's code I ran this snippet which also took about 45 minutes (no errors):

```
import { Client } from "xrpl";

const RPC_ENDPOINT = "wss://xrplcluster.com"; // TODO: Use this one again before the end
// const RPC_ENDPOINT = "wss://s.altnet.rippletest.net:51233/";
const client = new Client(RPC_ENDPOINT);

export const checkMLDBalance = async (
  xrp_address: string,
  avax_address: string,
  tx_hashes: string[]
) => {
  try {
    await client.connect();
    const res = await client.request({
      command: "account_tx",
      account: xrp_address,
      forward: false,
      binary: false,
      limit: 50,
    });

    /* internal logic */
    await client.disconnect();
  } catch (error) {
    console.log(error);
    return null;
  }
};

async function main() {
  const timeout = 0;
  for (let i = 0; i < 2000; i++) {
    console.log(i);
    await new Promise((resolve) => setTimeout(resolve, timeout));
    await checkMLDBalance("rJ6mzxnRNJYMUZ4nq8HxM2udKXrxDTVr9h", "abc", [
      "def",
      "ghi",
    ]);
  }
}

main();

const getXRPClient = () => {
  try {
    const _client = new Client(RPC_ENDPOINT);
    return _client;
  } catch (error) {
    console.log(error);
    return null;
  }
};
```

### Code Inspection

Here's what I looked for:
1. Since the error has `'reconnect'` in it, I looked for all instances of `reconnect` in the xrpl.js repo. 
    - All places where the connection is `'reconnect'` state have a `.catch` on them, so I'm not sure why it would propagate an error from them. 
        - Specifically [as part of logic to try automatically reconnecting if the connection was accidentally terminated](https://github.com/XRPLF/xrpl.js/blob/fa28b47111dc2e26cda466cfef5c03cb45cd358a/packages/xrpl/src/client/connection.ts#L521) and [on a heartbeat used to check if the connection is live, and if not, to reconnect](https://github.com/XRPLF/xrpl.js/blob/fa28b47111dc2e26cda466cfef5c03cb45cd358a/packages/xrpl/src/client/connection.ts#L554)
        - I did notice that the first spot the reconnect is used has a function with a very misleading name which should be revised (`this.intentionalDisconnect()`). While the name is backwards, the actual function actually does seem to reconnect and be used properly in the code as far as I can tell - [Usage](https://github.com/XRPLF/xrpl.js/blob/fa28b47111dc2e26cda466cfef5c03cb45cd358a/packages/xrpl/src/client/connection.ts#L493) / [Function definition](https://github.com/XRPLF/xrpl.js/blob/fa28b47111dc2e26cda466cfef5c03cb45cd358a/packages/xrpl/src/client/connection.ts#L512))

### Other Observations
1. I noticed that in both of your code examples - you are connecting and disconnecting the client before every request. That may just be because that's how you copied the code to make it work for a code reproduction, but if that's the case for other requests, maybe there's a race condition where a promise somewhere wasn't awaited. In that case, a shared client may end up being disconnected / reconnected intermittently leading to odd reconnect issues. (When I accidentally forgot an await when writing the reproduce code, every couple requests an `XrplError` and `ConnectionError` appeared. Since those aren't the same errors you're seeing though, I think this explanation is a bit of a long-shot)

------

All that being said, if you have a snippet which triggers the error consistently on your machine, that'd be super helpful since I'm not sure what else to look for currently. (Maybe those catch statements can help narrow down on the problematic line in the sample code)

**Comment by JST5000** [comment] 2023-08-11 17:25
Going to close for now as unable to reproduce, please re-open if you're able to reproduce locally and share the steps.

**Closed by JST5000** 2023-08-11 17:25 UTC

**Comment by justmoon** [comment] 2023-11-23 17:11
@mvadari @JST5000 

Ran into the same issue myself while working on [Dassie](https://github.com/justmoon/dassie):

```
4702.165 warn d2 stderr node:internal/errors:497
4702.165 warn d2 stderr     ErrorCaptureStackTrace(err);
4702.165 warn d2 stderr     ^
4702.165 warn d2 stderr 
4702.165 warn d2 stderr Error: Unhandled error. ('reconnect')
4702.165 warn d2 stderr     at __node_internal_captureLargerStackTrace (node:internal/errors:497:5)
4702.166 warn d2 stderr     at new NodeError (node:internal/errors:406:5)
4702.166 warn d2 stderr     at Client.emit (node:events:503:17)
4702.166 warn d2 stderr     at Connection.<anonymous> (/opt/workspace/justmoon/dassie/node_modules/.pnpm/xrpl@2.13.0/node_modules/xrpl/src/client/index.ts:245:12)
4702.166 warn d2 stderr     at Connection.emit (node:events:514:28)
4702.166 warn d2 stderr     at /opt/workspace/justmoon/dassie/node_modules/.pnpm/xrpl@2.13.0/node_modules/xrpl/src/client/connection.ts:555:14
4702.166 warn d2 stderr     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
4702.166 warn d2 stderr   code: 'ERR_UNHANDLED_ERROR',
4702.166 warn d2 stderr   context: 'reconnect'
4702.166 warn d2 stderr }
```

Basically, what's happening here is that in the `Connection` class there is logic to retry reconnection a number of times. If that fails, `Connection` emits an error event with code `reconnect`. See: https://github.com/XRPLF/xrpl.js/blob/4b9d50616735c7c009216b6e0aae81a19551a97a/packages/xrpl/src/client/connection.ts#L520-L524

That error is then reemitted on the Client object. See: 

https://github.com/XRPLF/xrpl.js/blob/4b9d50616735c7c009216b6e0aae81a19551a97a/packages/xrpl/src/client/index.ts#L246-L248

In Node.js `EventEmitter` if an event called `"error"` is emitted and there are no listeners, an exception is raised which may bubble up to the top of the stack and crash the process.

Steps to reproduce (haven't tested this but should work):

1. Connect xrpl.js client to the network. Don't register an event listener for the `"error"`  event.
2. Wait until successfully connected.
3. Unplug your network cable.
4. Wait until crash.

Suggested resolution:

Either handle reconnect errors in the Client object or improve documentation to make it clear that you need to listen to those events or risk your entire Node process crashing. Most of the examples I found in the docs did not include an `"error"` event listener. Note that there may be other types of errors (other than `"reconnect"`) that may cause the same issue.
